<a href="https://colab.research.google.com/github/Miyeon-Pyeon/bigdataanalysis_practice/blob/master/%EB%B9%85%EB%B6%84%EA%B8%B0_1025.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

In [3]:
DataUrl = 'https://raw.githubusercontent.com/Datamanim/pandas/main/Jeju.csv'
df = pd.read_csv(DataUrl,encoding='euc-kr')

In [4]:
df

,id,일자,시도명,읍면동명,거주인구,근무인구,방문인구,총 유동인구,평균 속도,평균 소요 시간,평균 기온,일강수량,평균 풍속
0,22448,2018-01-01,제주시,도두동,32249.987,3418.266,102709.092,138377.345,39.556,29.167,5.0,0.0,2.50
1,22449,2018-01-01,제주시,외도동,213500.997,10341.172,112692.789,336534.958,32.900,30.900,5.0,0.0,2.50
2,22450,2018-01-01,제주시,이도2동,1212382.218,96920.834,541194.481,1850497.533,29.538,35.692,2.9,0.0,2.40
3,22451,2018-01-01,제주시,일도1동,33991.653,6034.253,72155.919,112181.825,30.000,23.500,2.9,0.0,2.40
4,22452,2018-01-01,서귀포시,대천동,155036.925,9403.969,150882.409,315323.303,41.583,14.375,5.1,0.0,2.30
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9616,32064,2020-04-30,서귀포시,표선면,228260.005,16891.732,152832.449,397984.186,44.514,34.054,18.1,0.0,4.70
9617,32065,2020-04-30,제주시,한림읍,459959.064,26007.122,249700.419,735666.605,48.609,61.377,18.0,0.0,4.35
9618,32066,2020-04-30,제주시,도두동,28397.481,3144.895,84052.697,115595.073,41.053,29.421,20.3,0.0,3.00
9619,32067,2020-04-30,서귀포시,안덕면,348037.846,29106.286,251129.660,628273.792,46.595,49.189,17.6,0.0,3.50
9620,32068,2020-04-30,제주시,연동,1010643.372,65673.477,447622.068,1523938.917,40.863,27.765,14.1,0.0,4.80

In [5]:
# 데이터 마지막 3개행을 출력하라

df.tail(3)

,id,일자,시도명,읍면동명,거주인구,근무인구,방문인구,총 유동인구,평균 속도,평균 소요 시간,평균 기온,일강수량,평균 풍속
9618,32066,2020-04-30,제주시,도두동,28397.481,3144.895,84052.697,115595.073,41.053,29.421,20.3,0.0,3.0
9619,32067,2020-04-30,서귀포시,안덕면,348037.846,29106.286,251129.660,628273.792,46.595,49.189,17.6,0.0,3.5
9620,32068,2020-04-30,제주시,연동,1010643.372,65673.477,447622.068,1523938.917,40.863,27.765,14.1,0.0,4.8

In [9]:
# 수치형 변수를 가진 컬럼을 출력하라

# df.columns[int]  > 오답

df.select_dtypes(exclude=object).columns

Index(['id', '거주인구', '근무인구', '방문인구', '총 유동인구', '평균 속도', '평균 소요 시간', '평균 기온',
       '일강수량', '평균 풍속'],
      dtype='object')

In [13]:
# 범주형 변수를 가진 컬럼을 출력하라

df.select_dtypes(include=object).columns

Index(['일자', '시도명', '읍면동명'], dtype='object')

In [17]:
# 각 컬럼의 결측치 숫자를 파악해라

df.isnull().sum()

id          0
일자          0
시도명         0
읍면동명        0
거주인구        0
근무인구        0
방문인구        0
총 유동인구      0
평균 속도       0
평균 소요 시간    0
평균 기온       0
일강수량        0
평균 풍속       0
dtype: int64

In [ ]:
#